"""Canonical site data and geometry helpers."""

from .geometry import (
    PINNED_SHAPELY_VERSION,
    InvalidBoundaryError,
    area_m2,
    build_area_preserving_rectangular_placeholder,
    compute_area_m2,
    is_self_intersecting,
    polygon_from_geojson,
    polygon_to_geojson,
    validate_boundary,
    validate_self_intersection,
)
from .models import (
    BoundaryKind,
    BoundaryPolygon,
    CandidateAccessPoint,
    CoordinateOrigin,
    FrontageRoad,
    HypotheticalElevationPoint,
    ScenarioElevationOverride,
    ScenarioOverrideStatus,
    Setback,
    SiteModel,
    SourceFact,
    SourceReference,
    SourceTopographyState,
    SurveyedElevationPoint,
    Topography,
    TopographyRepresentation,
    TrueNorth,
    VerifiedArea,
)

__all__ = [
    "PINNED_SHAPELY_VERSION",
    "BoundaryKind",
    "BoundaryPolygon",
    "CandidateAccessPoint",
    "CoordinateOrigin",
    "FrontageRoad",
    "HypotheticalElevationPoint",
    "InvalidBoundaryError",
    "ScenarioElevationOverride",
    "ScenarioOverrideStatus",
    "Setback",
    "SiteModel",
    "SourceFact",
    "SourceReference",
    "SourceTopographyState",
    "SurveyedElevationPoint",
    "Topography",
    "TopographyRepresentation",
    "TrueNorth",
    "VerifiedArea",
    "area_m2",
    "build_area_preserving_rectangular_placeholder",
    "compute_area_m2",
    "is_self_intersecting",
    "polygon_from_geojson",
    "polygon_to_geojson",
    "validate_boundary",
    "validate_self_intersection",
]
