"""One-time editorial update for the user's explicit design delegation."""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
names = ["START_HERE_FOR_CODEX.md", "2026-09-11-amanda-tfg-bim-agent-design.md", "2026-09-11-amanda-tfg-bim-agent-COMBINED-plan.md", "PLAN_SELF_REVIEW.md", "docs/notes/2026-09-15-revisao-planos-handoff.md"]
texts = {n:(ROOT/n).read_text(encoding="utf-8") for n in names}

def change(name, old, new):
    if old not in texts[name]:
        raise ValueError(f"Target missing in {name}: {old[:90]}")
    texts[name] = texts[name].replace(old,new)

s,d,p,r,h = names
change(s, "A revisão documental não aprova uma alternativa arquitetônica nem autoriza executar automaticamente as instalações descritas.", "O usuário delegou ao agente a pesquisa e as decisões de projeto para futura execução, com revisão posterior por Amanda. Esta atualização registra essa delegação; implementação e instalações ainda não foram executadas.")
change(s, "- `TYPOLOGY`: confirmar o equipamento e sua política de sigilo/acesso.", "- `TYPOLOGY`: o agente pesquisa as referências e adota a solução institucional/de acessos mais coerente com o centro de acolhimento temporário e o programa de 20 pessoas; registra justificativa, fontes e possibilidade de revisão por Amanda.")
change(s, "- `SITE_BOUNDARY` e `SITE_OCCUPANCY`: confirmar polígono, frentes, área utilizável e premissa de realocação da ocupação existente.", "- `SITE_BOUNDARY` e `SITE_OCCUPANCY`: o agente pesquisa bases oficiais, mapas e documentos disponíveis, registra a melhor evidência e assume uma base provisória identificada quando faltar confirmação. Premissas de realocação e implantação são revisáveis; somente verificações dependentes da confirmação permanecem pendentes.")
change(s, "- `APPROVED_FOR_BIM`: a seleção detalhada depende de evidência humana vinculada ao hash do conteúdo. Massas de finalistas podem usar CONCEPT_ONLY somente até R04.", "- `APPROVED_FOR_BIM`: o agente pode selecionar e desenvolver a alternativa com `selection_authority = AGENT_DELEGATED`, justificativa e approval_hash. Amanda revisa depois (`AMANDA_REVIEW_PENDING`), sem bloquear a geração do BIM. CONCEPT_ONLY continua disponível para comparar massas até R04.")
change(s, "## Continuidade e integridade", "## Pesquisa e decisões delegadas\n\nO agente deve pesquisar, comparar alternativas, decidir e continuar, sem pedir confirmação rotineira sobre implantação, setorização, fluxos, materiais, linguagem ou preferência estética. Registrar as escolhas no futuro `project/requirements/decision-register.yaml`, com fontes, alternativas consideradas, motivo, limitações e arquivos afetados. Quando faltar evidência, usar `PROVISIONAL_ASSUMPTION` para o estudo; não apresentar hipótese como levantamento ou conformidade comprovada. O programa de 20 pessoas permanece fixo.\n\nAmanda pode mudar o que não gostar: criar nova revisão, manter a anterior e revalidar os elementos afetados. O agente não precisa aguardar esse retorno para desenvolver e apresentar a proposta.\n\n## Continuidade e integridade")
change(d, "or final architectural selection", "or external actions beyond current authorization; architectural research and selection are delegated to the agent as defined in section 6.15")
change(d, "- `TYPOLOGY`: confirmar o modelo institucional e sua política de sigilo/acesso com Amanda/orientadora; a revisão não resolve a contradição apenas renomeando casa-abrigo como centro.", "- `TYPOLOGY`: pesquisar referências institucionais e adotar pelo agente um modelo coerente com acolhimento temporário e proteção das usuárias; justificar a política de sigilo/acesso. Não basta renomear o equipamento: explicitar consequências espaciais e operacionais. Revisão de Amanda é posterior, não pré-condição para desenvolver o estudo.")
change(d, "Área escalar e imagem sem calibração não definem um lote executável.", "Área escalar e imagem sem calibração não comprovam um lote real executável. O agente pesquisa geometrias disponíveis e pode produzir uma reconstrução esquemática identificada como PROVISIONAL_ASSUMPTION para continuar o estudo, mantendo rastreável sua incerteza e substituição futura.")
change(d, "## 6.15 Human selection gate", "## 6.15 Delegated research and architectural decisions")
change(d, "Detailed production R05–R16 requires an explicit selection record with approver, timestamp, solution ID, `approval_hash` of canonical geometry/program/site/constraints/material intent, and evidence of the decision. `APPROVED_FOR_BIM` is valid only while these contents match. Any substantive change invalidates approval and returns the candidate for review.", """The user explicitly delegated research and architectural decisions on 2026-09-15: the agent researches, chooses and develops the proposal; Amanda may change it afterward. This delegation replaces the former mandatory human finalist-selection gate. Keep the selected PDF program for 20 people.

Detailed R05–R16 may proceed with `APPROVED_FOR_BIM`, `selection_authority = AGENT_DELEGATED`, decision timestamp, solution ID, rationale and `approval_hash` binding geometry/program/site/constraints/material intent. Here APPROVED_FOR_BIM means authorized for execution under delegated authority, not personally approved by Amanda or certified compliant. Store Amanda's review separately as `AMANDA_REVIEW_PENDING`; it does not block the agent's work. A later explicit acceptance can set AMANDA_ACCEPTED; requested changes create a new revision.

Research and decision workflow:

1. Search the supplied sources, then current official/primary sources for cadastral maps, urban rules, accessibility/fire requirements and institutional references. Record URLs or file hashes, version/date, article/page/map and applicability; follow material conflicts to their origin. Do not use this document as proof of a current legal rule.
2. Compare feasible alternatives using the fixed 20-person program, protection/privacy, flows, comfort, site evidence and constructability. Research precedents/material options and select the best justified proposal without asking routine preference questions.
3. Record each material choice in future `project/requirements/decision-register.yaml`: decision_id, topic, alternatives, selected option, rationale, source references, confidence, affected requirements/files, selection_authority, timestamp, supersedes, validation status and revision procedure.
4. If research cannot verify an input, choose a reversible `PROVISIONAL_ASSUMPTION` for a STUDY scenario and record its rationale/uncertainty. This is a treatment within DESIGN_HYPOTHESIS, not a fourth fact class. Keep actual survey/cadastral/normative verification pending and carry its affected-check list into BIM and reports. Hypothetical terrain levels may appear only in a clearly marked separate study scenario, never in VERIFIED_TOPOGRAPHY.
5. Continue unrelated tasks and detailed study development; missing preference, family layout, finish choice or uncertainty that can be represented provisionally must not stop the whole pipeline. Unknown mandatory compliance remains NOT_EVALUATED/BLOCKED_BY_INPUT and prevents an unsupported FINAL claim, not production of a labeled STUDY model.
6. Present the developed proposal with plans/previews and a concise decision summary. Amanda can revise it later; preserve previous sources, candidates, checkpoints and sealed releases. Her feedback takes precedence over delegated preferences. Regenerate the affected geometry/BIM/exports through a new version and re-run relevant checks. A substantive change invalidates the old hash; the agent may issue a new delegated decision after validation without waiting for another preference approval.

The agent selects typology, provisional site interpretation, implantation, massing, layouts, circulation, materials and design expression within the fixed brief. It does not fabricate official measurements, source statements, visits, legal compliance or Amanda's personal endorsement. Authentication, platform permissions and external actions outside existing authorization retain their own operational boundaries.""")
change(d, "- final architectural selection;\n- essential missing source data;", "- source data that cannot be researched or represented provisionally, only for the specifically dependent verified/final task; architectural preference and finalist selection are already delegated;")
change(d, "HUMAN SELECTION", "AGENT SELECTION")
change(d, "- silently deciding architecture;", "- hiding architectural decisions or claiming Amanda approved them personally; delegated decisions are recorded and revisable;")
change(d, "- silently choosing final architecture without a review gate;", "- hiding agent-made choices or falsely attributing approval to Amanda; use the delegated decision record and later review instead;")
change(d, "- require architectural selection before detailed BIM.", "- let the agent select and record the best justified architecture before detailed BIM, with Amanda's review afterward.")

change(p, "architecture selection and external data/publication boundaries.", "the delegated selection policy in design section 6.15 and external data/publication boundaries.")
change(p, "- [ ] Test `APPROVED_FOR_BIM` is explicit and not default.", "- [ ] Test APPROVED_FOR_BIM is explicit, content-bound and not default. AGENT_DELEGATED with valid decision evidence is eligible without Amanda approval; AMANDA_REVIEW_PENDING does not block BIM. Reject records falsely attributing personal approval or changing the fixed 20-person program.")
change(p, "- [ ] Record TYPOLOGY, PROGRAM_BASELINE, SITE_BOUNDARY, SITE_OCCUPANCY and REGULATION_APPLICABILITY decisions separately from the later finalist selection.", """- [ ] Record TYPOLOGY, PROGRAM_BASELINE, SITE_BOUNDARY, SITE_OCCUPANCY and REGULATION_APPLICABILITY separately from finalist selection in `project/requirements/decision-register.yaml`, following design section 6.15.
- [ ] Implement research tasks using available read-only search/source tools: official maps/cadastral material, applicable consolidated regulation/anexos and institutional/project references. Persist queries, sources, applicability and conclusions. The agent decides routine architectural questions without waiting for preferences.
- [ ] Test that AGENT_DELEGATED can select an evidence-backed option and continue; unverified data can be recorded as PROVISIONAL_ASSUMPTION within DESIGN_HYPOTHESIS for a STUDY scenario, never VERIFIED source data. Keep normative numbers from unverified sources out of verified hard constraints.
- [ ] Test that missing source input blocks only the affected verified check, while a separately labeled provisional study can proceed; FINAL stays blocked by unresolved mandatory verification. Test later replacement of the assumption propagates to affected geometry/BIM/exports and preserves prior versions.
- [ ] Test Amanda feedback creates a new decision revision, takes precedence over delegated preferences, invalidates obsolete approval_hash and schedules the dependent validations without overwriting protected originals/releases.""")
change(p, "- [ ] Record source-backed total site area/frontages.", "- [ ] Record source-backed total site area/frontages.") if "- [ ] Record source-backed total site area/frontages." in texts[p] else None
texts[p] = texts[p].replace("If no calibrated polygon/north exists, allow synthetic site work only; do not invent a rectangle of equal area.", "If no verified calibrated polygon/north exists after research, create an explicitly provisional study reconstruction with uncertainty/source rationale; never claim an equal-area rectangle is the real cadastral boundary. Separate the scenario geometry from verified site data.")
change(p, "- [ ] Preflight checks mode: CONCEPT_ONLY permits validated finalists through R04 only; SYNTHETIC_LAB permits marked fixtures; detailed production requires APPROVED_FOR_BIM with matching approval_hash, selected input versions, healthy registry and exact build.", "- [ ] Preflight checks mode: CONCEPT_ONLY permits finalists through R04; SYNTHETIC_LAB permits fixtures; detailed BIM permits APPROVED_FOR_BIM under AGENT_DELEGATED with matching approval_hash, decision evidence, selected input versions, healthy registry and exact build. AMANDA_REVIEW_PENDING is nonblocking. Real/unverified site input must be distinguished by STUDY profile and PROVISIONAL_ASSUMPTION; an unverified assumption cannot certify FINAL.")
change(p, "- [ ] Unapproved detailed production is rejected; CONCEPT_ONLY R00–R04 is allowed for eligible finalists and cannot promote a release. Test approval_hash invalidation on program/site/geometry changes.", "- [ ] Reject detailed BIM without a valid delegated or explicit human selection record. Accept AGENT_DELEGATED while AMANDA_REVIEW_PENDING; verify CONCEPT_ONLY remains limited to R04. Test hash invalidation after changed inputs, then validated agent reselection with a new decision/version, without another routine preference gate.")
change(p, "- `ARCHITECTURAL_SELECTION`;", "- `ARCHITECTURAL_SELECTION` only if the user later revokes delegation or explicitly requests a pause; currently disabled as a waiting gate;")
change(p, "- `ESSENTIAL_SOURCE_DATA`;", "- `ESSENTIAL_SOURCE_DATA` only for affected work after research and provisional-study alternatives are exhausted;")
change(p, "- `PROGRAM_BASELINE`.", "- `PROGRAM_BASELINE` only for a requested material change to the already selected 20-person brief.")
change(p, "- [ ] Routine package installation/provider fallback must not emit human gate.", "- [ ] Routine architectural choices, finalist selection, researched typology/materials and provisional STUDY assumptions must not emit a human gate under AGENT_DELEGATED. Routine package installation/provider fallback uses existing authorization and platform permissions.")
change(p, "Require resolved TYPOLOGY and valid SITE_BOUNDARY for the chosen production scope.", "Let the agent research and record TYPOLOGY and the best-supported SITE_BOUNDARY. If confirmation is unavailable, use a labeled provisional STUDY scenario and retain the corresponding verified/final checks as blocked; do not wait for aesthetic preferences.")
change(p, "### Task 9: Architectural selection gate [P08-T09]", "### Task 9: Delegated architectural selection and later Amanda review [P08-T09]")
change(p, "- [ ] Present top 3 to Amanda/Matheus.", "- [ ] Generate an up-to-three-finalist comparison and choose the most justified option autonomously under the fixed brief. Save previews/comparison for Amanda/Matheus to review afterward; do not wait for a reply to start detailed development.")
change(p, "- [ ] Record selected solution ID, approver, timestamp, approval evidence and approval_hash binding geometry/requirements/site/constraints and material intent. Changed content invalidates approval.", "- [ ] Record selected solution ID, selection_authority=AGENT_DELEGATED, decider=agent, timestamp, rationale, source/metric evidence and approval_hash binding geometry/requirements/site/constraints/material intent in decision-register. Set amanda_review=AMANDA_REVIEW_PENDING; do not imply personal approval. Changed content requires a new decision/hash and validation, which the agent may perform autonomously.")
change(p, "- [ ] If hybrid requested, create new solution", "- [ ] If a hybrid is justified by the agent or requested later by Amanda, create new solution")
change(p, "- [ ] Commit selection record.", "- [ ] Commit selection record and continue R05–R16 for the declared STUDY/FINAL scope. Later feedback creates a new version with affected-check revalidation; preserve the prior option/release and do not reopen the fixed 20-person capacity unless the user changes it.")

change(r, "## 4. Decisão do usuário e pendências de projeto", "## 4. Decisões do usuário e pesquisa delegada ao agente")
change(r, "| Tipologia/sigilo | Caderno e apoio discutem casa-abrigo/centro e visibilidade | Bloqueia adoção final da política de acessos/uso |", "| Tipologia/sigilo | Caderno e apoio discutem casa-abrigo/centro e visibilidade | Agente pesquisa e adota política justificada, revisável por Amanda depois |")
change(r, "| Lote/norte/confrontações | Área textual, ilustrações e hipóteses | Implantação real depende de base geométrica suficiente |", "| Lote/norte/confrontações | Área textual, ilustrações e hipóteses | Agente pesquisa fontes e prossegue em cenário STUDY provisório se necessário; confirmação do lote real segue rastreável |")
change(r, "| Arquitetura finalista | Sem seleção vinculada ao conteúdo verificada | Bloqueia R05–R16 detalhados de produção |", "| Arquitetura finalista | Pesquisa e seleção delegadas pelo usuário em 2026-09-15 | AGENT_DELEGATED + decisão/hash permite R05–R16; Amanda revisa posteriormente sem gate prévio |")
change(r, "As contradições foram registradas sem reescrever a pesquisa ou escolher premissas em nome da autora.", "As fontes permanecem intactas. Por instrução posterior do usuário, o agente deve pesquisar e escolher premissas/soluções revisáveis, registrando sua autoria e incertezas, sem atribuir endosso pessoal a Amanda.")
change(r, "**19 verificações; 19 passaram; 0 falharam**", "**21 verificações; 21 passaram; 0 falharam**")
change(r, "executa 19 verificações estáticas", "executa 21 verificações estáticas")
change(r, "grafo e IDs.", "grafo e IDs, além da delegação de seleção e tratamento de premissas revisáveis.")
change(r, "Essa escolha não autoriza automaticamente implementar o agente ou iniciar BIM detalhado.", "A instrução posterior delega ao agente pesquisa/decisões e permite desenvolver BIM sem aprovação estética prévia, quando a execução do plano ocorrer. Esta tarefa apenas atualizou os documentos; não implementou o sistema.")
texts[r] += "\n## 8. Delegação posterior de decisões\n\nEm 2026-09-15, o usuário determinou que o agente pesquise e tome decisões, deixando Amanda mudar depois o que não gostar. A seção 6.15 do design é o contrato canônico: seleção AGENT_DELEGATED, decision-register, hipóteses provisórias e revisão posterior não bloqueante. Essa instrução substitui o gate anterior de escolha humana; o programa de 20 pessoas continua adotado. Fontes, fatos, normas verificadas e hipóteses permanecem separados.\n\nValidação documental antes dessa mudança: 21 verificações, 19 passaram e 2 falharam pelas regras de delegação ausentes (validation-delegation-before.json). Depois, 21/21; exemplos e contratos de implementação continuam sem teste runtime. A futura implementação deve testar decisão delegada, hash inválido, hipótese não verificada e feedback de Amanda conforme as tarefas atualizadas.\n"
change(h, "4. PROGRAM_BASELINE já resolvido: PDF de 20 pessoas. Registrar seleção/hash na ingestão sem perguntar novamente. Resolver TYPOLOGY, SITE_BOUNDARY/SITE_OCCUPANCY, normas/topografia e seleção arquitetônica antes das tarefas dependentes.", "4. PROGRAM_BASELINE já resolvido: PDF de 20 pessoas. Pesquisa e decisões de TYPOLOGY, terreno, implantação, fluxos, materiais e seleção agora são delegadas ao agente, com registro de fontes e hipóteses; Amanda pode revisar depois sem bloquear desenvolvimento. Dados não verificáveis admitem cenário STUDY provisório; não comprovam FINAL.")
change(h, "a decisão de programa não é autorização para implementar ou selecionar arquitetura.", "a decisão de programa foi seguida pela delegação de pesquisa/seleção arquitetônica registrada abaixo; nenhuma implementação ocorreu nesta tarefa documental.")
texts[h] += """
## Continuação: pesquisa e decisões delegadas

Instrução explícita do usuário em 2026-09-15: colocar o agente para pesquisar e tomar decisões; Amanda muda depois se não gostar. Contrato vigente: design seção 6.15. O agente pode escolher tipologia, interpretação provisória do terreno, implantação, blocos, fluxos, layout e materiais, comparar/selecionar a alternativa e desenvolver BIM sem aguardar aprovação estética. PROGRAM_BASELINE de 20 pessoas permanece fixo.

Registrar seleção como AGENT_DELEGATED com rationale/fontes/approval_hash e AMANDA_REVIEW_PENDING separado. Persistir decisões no futuro project/requirements/decision-register.yaml; manter alternativas/versões e revalidar dependências após feedback. Ausência de dado verificável admite PROVISIONAL_ASSUMPTION dentro de DESIGN_HYPOTHESIS para STUDY, sem converter a premissa em levantamento, norma verificada ou aprovação pessoal de Amanda. FINAL continua exigindo evidência dos checks obrigatórios; só o check afetado fica bloqueado.

Alterados nesta continuação: quatro Markdown canônicos, este handoff e validate_documents.py; filhos/manifestações/ZIP regenerados. Backup prévio: docs/review/before-delegated-decisions. Script editorial one-shot apply_delegated_decisions.py registra a transformação; não rerodar sobre edições futuras.

Validação: validation-delegation-before.json = 21 checks, 19 passaram/2 falharam pelos novos contratos ausentes; validation-after.json = 21/21 após edição. package_review.py confere dez filhos, links e 22 hashes do pacote. Não houve pesquisa de projeto efetiva, escolha de implantação, instalação ou execução Revit: a autorização foi incorporada ao plano para o agente executar depois. GitHub sem commit/push: pasta segue sem Git/remoto; comandos anteriores continuam disponíveis. Próxima execução deve começar M1/01 e pesquisar/decidir autonomamente nas tarefas correspondentes, sem repetir perguntas de preferência já delegadas.
"""

for name,text in texts.items():
    (ROOT/name).write_text(text,encoding="utf-8")
print("Updated five documents for delegated research and decisions")
